export const Colors = {
  light: {
    background: '#F9F9F9',
    foreground: '#FFFFFF',
    buttonBackground: 'transparent',
    buttonBorder: '#E5E5E5',
    buttonHoverBackground: '#F2F2F2',
    sidebarActiveBackground: '#EDEDED',
    primaryText: '#171717',
    secondaryText: '#666666',
    componentBackground: '#F0F0F0',
    componentBackgroundHover: '#E8E8E8',
    componentBackgroundActive: '#E2E2E2',
  },
  dark: {
    background: '#0A0A0A',
    foreground: '#181818',
    buttonBackground: 'transparent',
    buttonBorder: '#242424',
    buttonHoverBackground: '#1F1F1F',
    sidebarDisabledText: '#A1A1A1',
    sidebarActiveText: '#EDEDED',
    primaryText: '#EDEDED',
    secondaryText: '#A1A1A1',
    componentBackground: '#181818',
    componentBackgroundHover: '#1F1F1F',
    componentBackgroundActive: '#242424',
  },
};
